### PR TITLE
IPv6 support in core

### PR DESCRIPTION
**Pull request by semirke**
Added OpenVZ VSwap support. Read comments.

Please guys review before pull.
Im using it but all my systems fully support IPv6.

### CODE REVIEW

**Comment by dterweij** [comment]
Thank you. Pull stays open for a while. I dont have ipv6 test systems yet.

**Comment by semirke** [comment]
Hi, 

 just the opposite! I do use it and it works on IPV6. 
 I dont know what with IPv4 systems

**Comment by semirke** [comment]
Hi, new diffs in request.

**Comment by semirke** [comment]
Please merge or discuss.

**Comment by dterweij** [comment]
Looks good, I hope that git handles my changes aswell in a good way in some of the same files :) if not then i revert and start them at my dev and use this one as base for some cleanups :)

**Comment by semirke** [comment]
If you find a merge problem, revert and I create a new pull req. I already merged mine with the current dev branch. So it should work.

Danny Terweij notifications@github.com írta:

> Looks good, I hope that git handles my changes aswell in a good way in
> some of the same files :) if not then i revert and start them at my dev
> and use this one as base for some cleanups :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lxcenter/hypervm/pull/40#issuecomment-23563194

## 

Ezt a levelet mobiltelefonról küldtem, K-9 Mail-el. Elnézést a levél rövidségéért és az esetleges hibákért.

**Pull request merged**
