### PR TITLE
Backport hotfix-LXSEC-2012-2 to lxcenter/hypervm@master

### PR DESCRIPTION
**Pull request by shakaran**
Backport hotfix-LXSEC-2012-2 to lxcenter/hypervm@master

### CODE REVIEW

**Comment by shazarlx** [comment]
Can you put this commit into your own issue branch and make a pull request to dev?  I'd like to test dev as a whole before we put anything more into master.

**Comment by shakaran** [comment]
I cannot make a pull request to hypervm/dev because the commit range will include my last pending request:
https://github.com/lxcenter/hypervm/pull/15

I am waiting to Danny or some core member checks for accept and then send the backported pull request to hypervm/dev

**Comment by shazarlx** [comment]
How can we avoid these conflicts in the future?  I am reviewing both pull requests and don't see how they overlap.

**Comment by shakaran** [comment]
It does not a conflict. It is a issue with how github handle the commits ranges.

If I try to make a pull request from lxcenter/shakaran@dev to lxcenter/hypervm@dev

It takes all the commits of my branch lxcenter/shakaran@dev still not merged with lxcenter/hypervm@dev, not a commit range of 2 or 3 commits.

**Comment by shakaran** [comment]
Oh, I just read (the section "How to customize the commit range") https://github.com/blog/612-introducing-github-compare-view

And I discover that it allows enter any branch, tag, or commit SHA1. So I can make the pull request to lxcenter/hypervm@dev too.

https://github.com/lxcenter/hypervm/pull/17

**Comment by shazarlx** [comment]
This is why you have to do issue branches.

----- Original Message ----- 
From: "Ángel Guzmán Maeso" 
reply@reply.github.com
To: "shazarlx" william.leonard@lxcenter.org
Sent: Wednesday, February 22, 2012 5:38 PM
Subject: Re: [hypervm] Backport hotfix-LXSEC-2012-2 to hypervm/master (#16)

**Comment by shazarlx** [comment]
So I will reject this one...

**Comment by shakaran** [comment]
This was perfectly valid to merge without any problem. So reopening.

**Comment by shazarlx** [comment]
Why though?  You made the same pull request to dev.  I thought we all agreed no pull request to master unless it is in dev first and tested?

**Comment by shazarlx** [comment]
This should be closed and once pull request 17 is merged into dev, it should be further tested and a pull request from dev to master should be made.

**Comment by shakaran** [comment]
It is a HOTFIX. It goes HOT for quickly FIX a urgent problem. It is the exception to the rule. Or do you think that it is better put it dev a week or two days ... and get a hundred of systems hacked while we wait testing and then it could be into master? Did you get my point?

**Comment by shazarlx** [comment]
No need for an exception though.  Let's close the master one I will accept the pull to dev now and then you can make a pull request from dev to master and I will accept that right now...

**Comment by shazarlx** [comment]
YOu can use your commit range trick on the dev to master pull request...

**Comment by shakaran** [comment]
You don't need close any pull request and I don't need make another range selection commit. There are not any problem accepting master first or dev first because all commits proceed from the same branch issue hotfix-LXSEC-2012-2

If you want accept first the #16 (dev) or #17 (master) it is the same. Both commits _MUST_ be on both branches because it is a hotfix. We are late 10 hours now. A hotfix should <1h accepted.

**Comment by shazarlx** [comment]
Can you join IRC.  I am really misunderstanding something hear and I want to 
clear it up.

-Will

----- Original Message ----- 
From: "Ángel Guzmán Maeso" 
reply@reply.github.com
To: "shazarlx" william.leonard@lxcenter.org
Sent: Wednesday, February 22, 2012 10:25 PM
Subject: Re: [hypervm] Backport hotfix-LXSEC-2012-2 to 
lxcenter/hypervm@master (#16)

**Pull request merged**
