### PR TITLE
Debian C files support and remove errors.

### PR DESCRIPTION
**Pull request by shakaran**
Add full Debian support to C files. Compile with pedantic, ansi C99 and remove errors.

### CODE REVIEW

**Comment by dterweij** [comment]
Did you test this on CentOS 5.7 also? because it does only compile lxxen and nothing more.

**Comment by dterweij** [comment]
[root@testserver src]# make
gcc -Wall -ansi -pedantic -Wextra -Werror  -g lxlogin.c lxxen.c -o lxxen
[root@testserver src]# ls -l
total 68
-rwxr-xr-x 1 lxlabs lxlabs  2057 Nov 20 18:11 losetup.c
-rw-rw-r-- 1 lxlabs lxlabs  1353 Nov 20 18:11 losetup.h
-rwxr-xr-x 1 lxlabs lxlabs  1268 Nov 20 18:11 lxlogin.c
-rw-rw-r-- 1 lxlabs lxlabs  1174 Nov 20 18:11 lxlogin.h
-rwxr-xr-x 1 lxlabs lxlabs  1021 Nov 20 18:11 lxopenvz.c
-rwxr-xr-x 1 lxlabs lxlabs  2161 Nov 20 18:11 lxrestart.c
-rw-rw-r-- 1 lxlabs lxlabs  1270 Nov 20 18:11 lxrestart.h
-rwxr-xr-x 1 root   root    9868 Nov 20 18:23 lxxen
-rwxr-xr-x 1 lxlabs lxlabs  1214 Nov 20 18:11 lxxen.c
-rw-rw-r-- 1 lxlabs lxlabs  1792 Nov 20 18:11 Makefile
-rw-rw-r-- 1 lxlabs lxlabs 14098 Nov 20 18:11 program-backend.c
-rw-rw-r-- 1 lxlabs lxlabs  2846 Nov 20 18:11 program-backend.h

**Comment by shakaran** [comment]
Yes, I test too on CentOS 5.7 machine.

You have to use the "all" option. Also you can compile individually the components (for test and development or a update requirement). You can see all the make options available writing "make" and pressing "TAB" key two times.

For example:
$ make 
all       backend   clean     freeloop  install   Makefile  openvz    restart   xen  
$ make xen
gcc -Wall -ansi -pedantic -Wextra -Werror  -g lxlogin.c lxxen.c -o lxxen
$ make openvz
gcc -Wall -ansi -pedantic -Wextra -Werror  -g lxlogin.c lxopenvz.c -o lxopenvz
$ make freeloop 
gcc -Wall -ansi -pedantic -Wextra -Werror  -g losetup.c -o findfreeloop 
$ make restart 
gcc -Wall -ansi -pedantic -Wextra -Werror  -g lxrestart.c -o lxrestart 
$ make backend 
gcc -Wall -ansi -pedantic -Wextra -Werror  -g -o hypervm.exe program-backend.c -I/usr/include -lssl
$ make all
gcc -Wall -ansi -pedantic -Wextra -Werror  -g lxlogin.c lxxen.c -o lxxen
gcc -Wall -ansi -pedantic -Wextra -Werror  -g lxlogin.c lxopenvz.c -o lxopenvz
gcc -Wall -ansi -pedantic -Wextra -Werror  -g losetup.c -o findfreeloop 
gcc -Wall -ansi -pedantic -Wextra -Werror  -g lxrestart.c -o lxrestart 
gcc -Wall -ansi -pedantic -Wextra -Werror  -g -o hypervm.exe program-backend.c -I/usr/include -lssl

**Comment by dterweij** [comment]
If changes are made like this, also change the depencies :)
Other files are doing: make ; make install

**Comment by dterweij** [comment]
anyway make all shows:

[root@testserver src]# make all
gcc -Wall -ansi -pedantic -Wextra -Werror  -g lxlogin.c lxxen.c -o lxxen
gcc -Wall -ansi -pedantic -Wextra -Werror  -g lxlogin.c lxopenvz.c -o lxopenvz
gcc -Wall -ansi -pedantic -Wextra -Werror  -g losetup.c -o findfreeloop
In file included from losetup.h:33,
                 from losetup.c:21:
/usr/include/linux/loop.h:45: error: expected specifier-qualifier-list before â__u64â
make: **\* [freeloop] Error 1

**Pull request merged**
