### PR TITLE
Prevent deleting hypervm-*.zip when using development version

### PR DESCRIPTION
**Pull request by dterweij**
Lets hope i can now install the dev version from this branch :) (Installing to Sponsored server at CastleGem)

### CODE REVIEW

**Comment by dterweij** [comment]
Okay finaly works on 1 small problem. yum reinstall lxzend because somehow hypervm does not start because of missing zend extention. I thought i removed that but i might have missed something :) After install, keep uptodate with git pull (if still in dev branch, you can switch to master also).

Now i go to sleep :)

**Comment by semirke** [comment]
So will git installation be the default?

**Comment by dterweij** [comment]
Op 21-8-2013 14:03, semirke schreef:

> So will git installation be the default?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/lxcenter/hypervm/pull/48#issuecomment-23012148.

Is a way to install if master keeps equal to the zip release.
And much faster to get a patch on a production system when it is 
important to have.

It is at first instance just a easy way to install a working and running 
dev branch where you can develop on.
And test the master branch before a release :)

It definitly does not work as a update to an existing running system. 
Only for new installs.

Besides that all, i am not sure if HyperVM open source code equals to 
the closed source code. Before the first release, we have to make sure 
that everything and everything works as excpected. That was _NOT_ the 
case with Kloxo. There we had to make some adjustments as we had 
something in the middle of something code :)

At first sight, HyperVM dev branch works. It is running, we have a GUI. 
But if all else works as expected, i dont know yet :)

Regards,
Danny.

**Comment by semirke** [comment]
Im using the dev branch in _production_ for around 1.5 half years.
(Only with openvz)

**Comment by dterweij** [comment]
Op 27-8-2013 1:01, semirke schreef:

> Im using the dev branch in /production/ for around 1.5 half years.
> (Only with openvz)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/lxcenter/hypervm/pull/48#issuecomment-23301961.
> 
> Does this working: VM Home, Backup Home:

Press the map icon to select a file to restore from. What happens at 
your dev ?
At my dev, nothing happens. Seems javascript is broken?
Needs to popup a open file dialog.

Danny.

**Comment by semirke** [comment]
Hi,
 Dont use javascript, only for clients.
  Never restored a vps. But Ill test these function. 
  I really dont want hypervm to die.

Semir

Danny Terweij notifications@github.com írta:

> Op 27-8-2013 1:01, semirke schreef:
> 
> > Im using the dev branch in /production/ for around 1.5 half years.
> > (Only with openvz)
> > 
> > —
> > Reply to this email directly or view it on GitHub 
> > https://github.com/lxcenter/hypervm/pull/48#issuecomment-23301961.
> > 
> > Does this working: VM Home, Backup Home:
> 
> Press the map icon to select a file to restore from. What happens at 
> your dev ?
> At my dev, nothing happens. Seems javascript is broken?
> Needs to popup a open file dialog.
> 
> Danny.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lxcenter/hypervm/pull/48#issuecomment-23445153

## 

Ezt a levelet mobiltelefonról küldtem, K-9 Mail-el. Elnézést a levél rövidségéért és az esetleges hibákért.

**Pull request merged**
