### PR TITLE
Update #3 for core-clean1 round

### PR DESCRIPTION
**Pull request by shakaran**
It cleans and optimize the function methods getDiskUsage(), initXenVars(), doSyncToSystemPre(), checkVPSLock() on vps__xenlib.php.

Remove some deprecated functions like lxfile_get_ntfs_disk_usage() for Windows and winflags added.

Also ident the file vps__openvzlib.phps with method functions idented.

### CODE REVIEW

**Comment by shazarlx** [comment]
Why is lxfile_get_ntfs_disk_usage() deprecated?  Is there another function that is giving the disk usage of Windows domUs?

**Comment by shakaran** [comment]
The Windows related code is being removed by Danny too. I just remove too the function for the disk usage.

**Comment by shazarlx** [comment]
You've misunderstood what Danny is doing.  Danny is removing Windows related stuff as it pertains to the host system of Kloxo, which of course with Kloxo should be anything.  With HyperVM Windows is only a guest domU.  Any Windows related code must be kept or you remove a very usable and current feature of HyperVM.  I have actually been working on code to allow Windows 2008 to work as a guest and plan on more features for better backup and such.

Many people use HyperVM to host Windows Server 2003 currently.

*edited changed work as a host to work as a guest.

**Comment by shakaran** [comment]
Ok, I understand now. I will commit again and apply the code related to Windows host, but optimizing the old code.

**Comment by shazarlx** [comment]
My test system does not have VT-X, so I can't test Windows changes easily.  My only concern is that this open source repo is not fully tested in the field at all and all these changes are being made without the proper testing.  When I used this open repo in the past, I had problems, so I am only using the stable release and a few open files as needed, like the xen lib for example.

**Comment by shazarlx** [comment]
Actually I may have a machine now with VT-X.  So let me know when this commit is done and hopefully I can test it out soon.

**Comment by shakaran** [comment]
The commits related for windows host is pushed. Waiting more reviews comments or accept the pull request

**Comment by dterweij** [comment]
Indeed, Windows code can be removed if only related to Host HyperVM on a Windows server. That code was never finished and not working well, not at all, ugly coded. Windows code for Xen Windows Guests has to stay :)

Reviewing.

**Pull request merged**
