### PR TITLE
pygrub support

### PR DESCRIPTION
**Pull request by shazarlx**
Please pull a5bf9953b95e7c4cee30b0e5e3d73ad93ce1cdd9 to dev.

### CODE REVIEW

**Comment by shazarlx** [comment]
That is to say the original commit is on this page and then the changes with some new lines added and changed some double quotes to single quotes.

**Comment by shazarlx** [comment]
See right here:

782  782     //Add pygrub configuration if template name contains pygrub 
783     -  $pygrub_r = explode("-", $this->main->ostemplate); 
784     -  if (stripos($pygrub_r[3], "pygrub") !== FALSE) 
785     -    $string .= "kernel = '';root = '';bootloader = '/usr/bin/pygrub'\n"; 
   783  +  $pygrub_r = explode('-', $this->main->ostemplate); 
   784  +  if (stripos($pygrub_r[3], 'pygrub') !== FALSE) 
   785  +    $string .= "kernel = '';\nroot = '';\nbootloader = '/usr/bin/pygrub'\n";

**Comment by shakaran** [comment]
Still not fine. For proceed you need stil fix this:

-What means $pygrub_r? The name is confusing. => You still not provide a explanation
-You should use brackets too for single if lines. => on the code that I purpose you, I put if () { }. You are still missing it
- Use PHP_EOL instead of /n. => PHP_EOL is multiplataform. \n doesn't work fine with all operating systems. PHP made that for you with the constant PHP_EOL.
- Change double quotes by single quotes. => You still are using double quotes on $string var. Inside of string you can escape single quotes for kernel, root and bootloader assignements.

**Comment by shazarlx** [comment]
This entire file I modified uses the /n and I don't see that on the standards page.

I am following the code standards for the $string line I did.

**Comment by shazarlx** [comment]
Sorry ... uses \n.

**Comment by shazarlx** [comment]
How about now?

**Comment by shakaran** [comment]
I send a modification for RFC 2 to core list respecting PHP_EOL vs /n. The old code is bad structured and it doesn't complain the stantdars, I know, but the new have to follow.

Regarding the standard for double quotes, you have to used single quotes. And maybe it is better for read purposes like this:

<pre>
// Add pygrub configuration if template name contains pygrub
$pygrub_r = explode('-', $this->main->ostemplate);

if (stripos($pygrub_r[3], 'pygrub') !== FALSE) {
    $string .= 'kernel = \'\';' . PHP_EOL .
                   'root = \'\';' . PHP_EOL .
                   'bootloader = \'/usr/bin/pygrub\'' . PHP_EOL;
}
</pre>


Still I need know what do you mean with $pygrub_r, it's $pygrub_read?

**Comment by shazarlx** [comment]
So you'll make RFCs just to deny my pull requests?  Does this mean not a 
single release should be made that doesn't use PHP_EOL?

-Will

----- Original Message ----- 
From: "Ángel Guzmán Maeso" 
reply@reply.github.com
To: "shazarlx" william.leonard@lxcenter.org
Sent: Sunday, January 22, 2012 11:52 AM
Subject: Re: [hypervm] pygrub support (#8)

**Comment by shazarlx** [comment]
_r is a way to dictate it is an array.

**Comment by shakaran** [comment]
Accepting pull request. With pending discussion about PHP_EOL for core members and I gonna skip for the moment the double quotes for the $string.

**Comment by shazarlx** [comment]
Angel,

```
I am going to make a pull request from master to dev and pull it myself 
```

ok?  As you already pulled the request I see no problem with it.  Evreyone 
can put in a vote if they'd like;)

-Will

----- Original Message ----- 
From: "Will" william.leonard@lxcenter.org
To: "Ángel Guzmán Maeso" 
reply@reply.github.com; 
lxdevel@googlegroups.com; core@lists.lxcenter.org
Sent: Sunday, January 22, 2012 11:56 AM
Subject: [Developers] Re: [hypervm] pygrub support (#8)

So you'll make RFCs just to deny my pull requests?  Does this mean not a
single release should be made that doesn't use PHP_EOL?

-Will

----- Original Message ----- 
From: "Ángel Guzmán Maeso"
reply@reply.github.com
To: "shazarlx" william.leonard@lxcenter.org
Sent: Sunday, January 22, 2012 11:52 AM
Subject: Re: [hypervm] pygrub support (#8)

> I send a modification for RFC 2 to core list respecting PHP_EOL vs /n. The 
> old code is bad structured and it doesn't complain the stantdars, I know, 
> but the new have to follow.
> 
> Regarding the standard for double quotes, you have to used single quotes. 
> And maybe it is better for read purposes like this:
> 
> <pre>
> // Add pygrub configuration if template name contains pygrub
> $pygrub_r = explode('-', $this->main->ostemplate);
> 
> if (stripos($pygrub_r[3], 'pygrub') !== FALSE) {
>    $string .= 'kernel = \'\';' . PHP_EOL .
>                   'root = \'\';' . PHP_EOL .
>                   'bootloader = \'/usr/bin/pygrub\'' . PHP_EOL;
> }
> </pre>
> 
> 
> Still I need know what do you mean with $pygrub_r, it's $pygrub_read?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lxcenter/hypervm/pull/8#issuecomment-3604084

## 

# http://en.wikipedia.org/wiki/Netiquette

# A: Because it messes up the order in which people normally read text.

# Q: Why is top-posting such a bad thing?

# A: Top-posting.

# Q: What is the most annoying thing in e-mail?

# To Unsubscribe, send an e-mail to:

# lxdevel+unsubscribe@googlegroups.com

#

# For more options, visit:

# http://groups.google.com/group/lxdevel

# At december, 11th 2011: 21 members subscribed to this list.

**Pull request merged**
