### PR TITLE
Update lang

### PR DESCRIPTION
**Pull request by dterweij**
Added/Updated  HyperVM Languages.

### CODE REVIEW

**Comment by shakaran** [comment]
It seem's ok, but a lot vars are using double quotes. Could you make a quickly replacement? (Maybe you need scape with \' some single quotes, specially on FR)

**Comment by dterweij** [comment]
Thats a lot work.. Need to teach translators with a proper document  :)

This is the first commit that is doing as you and i want :)

**Comment by shakaran** [comment]
Well I will accept. But only because this files will be a replacement for gettext. Next time, if others(translators) don't follow the coding standars it will need update the files before to add into a pull request.

**Comment by dterweij** [comment]
Yes that will be the case the next time.

**Pull request merged**
