### PR TITLE
Core clean round 1

### PR DESCRIPTION
**Pull request by shakaran**
This a example to follow for core members development cleans.

It mostly add php-doc comments to class and a couple of function methods. Also rewrite the var old naming and check empty values on list or arrays no initialized.

### CODE REVIEW

**Comment by andrewying** [comment]
Unfortunately, this is not completely a good example. Where is the GNU AGPL license info? Refer to RFC 2 for more details. 

And also, I'm not sure if this is due to your time taken on this example, but I can find something like this:
`$this->main->maindisk = "/dev/$vgname/{$this->main->maindiskname}";` in line 196 of hypervm/httpdocs/lib/vps/driver/vps__xenlib.php. This should be changed, isn't it?

**Comment by shazarlx** [comment]
Angel - This is sort of what I have been talking about when I say I only change what needs to be changed.  You've turned a string with a constant into a literal.  Have you tested each of the things that you are requesting a pull for?

**Comment by shakaran** [comment]
@andrewying The GNU AGPL license info is on the header of vps__xenlib.php. I don't know what you mean refering to RFC 2.
The string that you refer only is showed as modified because I change the identation on method, but nothing more (see first commit). I don't rewrite the method initXenVars() on vps__xenlib.php, only the methods find_traffic() and find_cpuusage(). I test on my machine the changes without problems.

@shazarlx please could you specify exactly what string with a constant? I don't see any variable declared as constant.

**Comment by shazarlx** [comment]
Maybe not a constant, but a variable.  The ones I see start with __program.

**Comment by shazarlx** [comment]
Sorry... I really don't know haha.  Maybe HyperVM uses that string and replaces it on the fly?

**Comment by shakaran** [comment]
@shazarlx Exactly. Kloxo and HyperVM translate some "tokens" strings of paths. Putting double quoted or single quoted doesn't affect. That is a possible thing to remove fully, because the tokens for paths are dangerous and take more time to process the strings when the app core have to parse and found every token. On my QPanel fork of Kloxo I remove the 80% of them and the speed using paths is 3x superior, saving around 300 ms on each normal call.

**Comment by shazarlx** [comment]
@shakaran - Ok, is it ok for me to pull this into dev now?  We would then have as many people as possible test this before moving it to master, right?

**Comment by shakaran** [comment]
@shazarlx Yes, I am pulling requesting this to lxcenter/hypervm@dev. I just wait the accept confirmation of @andrewying

**Comment by andrewying** [comment]
@shakaran 

I'm sorry for that. But next time, do not remove the core-clean1 branch until your pull request is being accepted. This help me finding the exact modified version of the file. But anyway, a great example :)

 I only have a comment on commit 2baf265 on the use of @version. Please kindly review it. If you have changed this then my position will be accepting this. Or maybe you can convince me of using 1.0 for @version :)

**Comment by shakaran** [comment]
@andrewying I don't remove my branch core-clean1 https://github.com/shakaran/hypervm/tree/core-clean1 is still alive and kicking, maybe you lost the link reference?

I modify the @version php-doc issue. My opinion is that version file is not very important (just for doc generation purposes) and we still don't define nothing at respect, but it is ok, no problem adding the build date. Nice review. If all it is ok, you can accept it.

**Comment by andrewying** [comment]
Emm quite odd. Anyway, merged the pull request.

**Pull request merged**
